# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e483ea5b0f7d01864f7c7fce4b461f9339705162fb8fec90d739590ffb676b66f5e832a7303d5002247c4c924abbed382ab1b92b426746359add6b3fb39970

test:
  secret_key_base: ce490947fd0fd47a1c1c5af4c8486c90d10ed9a6c0c54ecd5c1047f5a9edcb17978131f7d0a4d9122291be5ba4ceb7932e806f117defb42980785f410c169842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
